---
- hosts: localhost
  tasks:
    - name: Pull Docker frontend image from Docker Hub
      docker_image:
        name: tezaswa/client
        tag: latest
        source: pull

    - name: Pull Docker backend image from Docker Hub
      docker_image:
        name: tezaswa/server
        tag: latest
        source: pull

    - name: Run Docker container for frontend
      docker_container:
        name: client
        image: tezaswa/client:latest
        ports:
          - "5173:5173"
        state: started

    - name: Run Docker container for backend
      docker_container:
        name: server
        image: tezaswa/server:latest
        ports:
          - "8081:8081"
        state: started
