---
- hosts: localhost
  tasks:
    - name: Pull Docker frontend image from Docker Hub
      docker_image:
        name: tezaswa/client
        tag: latest
        source: pull

    - name: Pull Docker backend image from Docker Hub
      docker_image:
        name: tezaswa/library_managment_system_backend
        tag: latest
        source: pull

    - name: Run Docker container for frontend
      docker_container:
        name: library_managment_system_frontend
        image: tezaswa/client:latest
        ports:
          - "5173:5173"
        networks:
          - name: host
        state: started

    - name: Run Docker container for backend
      docker_container:
        name: library_managment_system_backend
        image: tezaswa/library_managment_system_backend:latest
        ports:
          - "8081:8081"
        networks:
          - name: host
        state: started
