apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: library-management
spec:
  selector:
    app: server 
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8081
  type: LoadBalancer

